language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - memcached
env:
  global:
    - REPORT_EXIT_STATUS=1
before_script:
  - mysql -e 'CREATE DATABASE `cscms.travis`;'
  - echo 'yes' | pecl install apcu-beta
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - apt-get install -qq php5-mcrypt
  - echo 'extension = mcrypt.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: php run-tests.php -P --show-diff tests
