language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
services:
  - memcached
env:
  global:
    - REPORT_EXIT_STATUS=1
before_script:
  - mysql -e 'CREATE DATABASE `cscms.travis`;'
  - echo 'yes' | pecl install apcu-beta
  - php -v | grep -q 'PHP 7.0' && echo 'yes' | pecl install memcached
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: php run-tests.php -P --show-diff tests
