language: php
php:
  - 5.4
  - 5.5
  - 5.6
services:
  - memcached
env:
  global:
    - REPORT_EXIT_STATUS=1
before_script:
  - mysql -e 'CREATE DATABASE `cscms.travis`;'
  - echo 'no' | pecl install apcu
  - phpenv config-add tests/$TRAVIS_PHP_VERSION.ini
script: php run-tests.php -P --show-diff tests
