language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
matrix:
  allow_failures:
    - php: 7.0
sudo: false
services:
  - memcached
env:
  global:
    - REPORT_EXIT_STATUS=1
before_script:
  - mysql -e 'CREATE DATABASE `cscms.travis`;'
  - echo 'yes' | pecl install apcu-beta
  - php -v | grep -q 'PHP 7.0' || echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
success_script:
  - php -d phar.readonly=Off upload_build.php
script: php run-tests.php -P --show-diff tests
