language: php
php:
  - 5.6
  - 7.0
sudo: false
services:
  - memcached
env:
  global:
    - REPORT_EXIT_STATUS=1
  matrix:
    - DB=MySQLi
    - DB=SQLite
matrix:
  allow_failures:
    - env: DB=SQLite
before_script:
  - mysql -e 'CREATE DATABASE `cscms.travis`;'
script:
  - php -d variables_order=EGPCS run-tests.php -P --show-diff tests
after_success:
  - php -d variables_order=EGPCS -d phar.readonly=Off upload_build.php
